---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test
  region: eu-west-2

nodeGroups:
  - name: ng1-public
    instanceType: t3.micro
    desiredCapacity: 2

managedNodeGroups:
  - name: ng2-managedNodeGroups
    instanceType: t3.micro
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
