--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test
  region: eu-west-2

managedNodeGroups:
  - name: ng-application
    instanceType: t3.micro
    iam:
      withAddonPolicies:
        autoScaler: true
    minSize: 0
    maxSize: 10
    desiredCapacity: 0
    # comment out taints since having trouble getting to work
    #taints:
    #  - key: application
    #    value: "nginx"
    #    effect: NoExecute
    labels:
      application: "nginx"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eksctl-test: "true"
      k8s.io/cluster-autoscaler/node-template/label/application: "nginx"
      #k8s.io/cluster-autoscaler/node-template/taint/application: "nginx:NoExecute"
